### ISSUE TITLE
eos-update

### ISSUE THREAD

**Issue by ringo32** [EndeavourOS-Community-Editions/sway#82]
eos-update does not show up in fuzzel.

while in my rofi-wayland and nwg launcher does :)

**Comment by BluishHumility** [comment]
That is intentional actually. It is not caused by fuzzel, but rather by the desktop files in `~/.local/share/applications`: https://github.com/EndeavourOS-Community-Editions/sway/commit/aa3802ae5c4fe31e54fec7c5d2681e65d42572a7#diff-18b6c45bf1bdd7271c551a36f2a6eeabc4543d20e98924b713ab958071b8efd8

The local desktop files with `NoDisplay=true` are an effort to declutter the launcher's menu by hiding default applications which are intended to be launched from within another application. In addition to being able to be run directly from the terminal, `eos-update` also has a launcher inside the EOS Welcome application so it was included in this effort.

If you would like to restore `eos-update` (or any of these other applications) to the launcher, you can just delete the local desktop file for it.

```
rm ~/.local/share/applications/eos-update.desktop
```
